python3 src/1_data.py #--list_dir_train 'your_path' --list_dir_test 'your_path' --save_dir 'your_path' --max_length 'your num'
python3 src/2_train.py # --train_data_path 'your path' --new_model_path 'your path' --max_length 'your num' --batch_size 'your num' --epochs 'your num' --learning_rate 'your num'
python3 src/3_infer_corr.py # --model_path 'your path' --input_file 'your path' --output_dir 'your path' --max_length 'your num' --rate 'your rate'
python3 src/4_infer_trans.py # --model_path 'your path' --input_file 'your path' --output_dir 'your path' --max_length 'your num'
python3 src/5_eval_corr.py # --input_path 'your path'
python3 src/5_eval.py # --input_path 'your path'
